kind: Certificate
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: k8s.bb-app.cn
spec:
  secretName: k8s.bb-app.cn-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: k8s.bb-app.cn
  dnsNames:
  - k8s.bb-app.cn
  acme:
    config:
    - http01:
        ingress: letsencrypt-k8s.bb-app.cn
      domains:
      - k8s.bb-app.cn